### ISSUE TITLE
Hints & placeholders for fields

### ISSUE THREAD

**Issue by pshemekm** [WPChill/gutenberg-forms#134]
Hi, I think that a possibility of writing small hints under fields would be very helpful for users.
Also HTML placeholders for inputs are in a common use.

**Comment by munirkamal** [comment]
Yeah, you are correct, it should have instructions in the editor as well as proper documentation (which I haven't able to start on yet).

Adding it to do list.

**Comment by macemmek** [comment]
OK, you're right with the documentation but I actually meant a hint (and placeholder attr) as a field feature.
Like: "Please keep file <10MB" under upload field, etc.
