### ISSUE TITLE
Guteberg Form Not working

### ISSUE THREAD

**Issue by dumketo** [WPChill/gutenberg-forms#172]
Hello,
I can't use this plugin properly on WordPress new version. Can't add new field also don't show me import form. I don't understand why is it happen. Please help me.

Got those errors::
[DOM] Found 2 elements with non-unique id #_wpnonce: (More info: https://goo.gl/9p2vKq) <input type=​"hidden" id=​"_wpnonce" name=​"_wpnonce" value=​"b15464790d">​ <input type=​"hidden" id=​"_wpnonce" name=​"_wpnonce" value=​"13b2860d92">​
editor.jsx:45 Uncaught (in promise) TypeError: Cannot read property 'render' of undefined
    at editor.jsx:45
blocks.min.js:3 Block "core/paragraph" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/image" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/heading" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/gallery" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/list" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/quote" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/shortcode" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/archives" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/audio" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/button" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/buttons" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/calendar" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/categories" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/code" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/columns" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/column" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/cover" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/embed" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/twitter" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/youtube" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/facebook" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/instagram" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/wordpress" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/soundcloud" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/spotify" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/flickr" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/vimeo" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/animoto" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/cloudup" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/collegehumor" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/crowdsignal" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/dailymotion" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/imgur" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/issuu" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/kickstarter" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/meetup-com" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/mixcloud" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/polldaddy" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/reddit" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/reverbnation" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/screencast" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/scribd" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/slideshare" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/smugmug" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/speaker" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/speaker-deck" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/tiktok" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/ted" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/tumblr" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/videopress" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/wordpress-tv" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core-embed/amazon-kindle" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/file" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/group" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/freeform" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/html" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/media-text" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/latest-comments" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/latest-posts" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/missing" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/more" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/nextpage" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/preformatted" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/pullquote" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/rss" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/search" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/separator" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/block" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/social-links" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/social-link" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/spacer" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/subhead" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/table" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/tag-cloud" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/text-columns" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/verse" is already registered.
Te @ blocks.min.js:3
blocks.min.js:3 Block "core/video" is already registered.
Te @ blocks.min.js:3
update-block-list.js:28 Uncaught TypeError: Cannot read property 'render' of undefined
    at update-block-list.js:28
    at Array.forEach (<anonymous>)
    at window.onload (update-block-list.js:13)
deprecated.min.js:2 Button isDefault prop is deprecated. Please use isSecondary instead.
c @ deprecated.min.js:2
deprecated.min.js:2 wp.components.IconButton is deprecated. Please use wp.components.Button instead.
c @ deprecated.min.js:2
![form](https://user-images.githubusercontent.com/1678482/92554601-8be88680-f287-11ea-85bd-6aa5a7f9eba4.png)
![plugin list](https://user-images.githubusercontent.com/1678482/92554602-8d19b380-f287-11ea-8fec-7d81fcfe8d74.png)

**Comment by ZafarKamal123** [comment]
Hey @dumketo,

This seems an issue caused by another plugin. Please try de-activating every plugin one by one?

**Comment by enrique71** [comment]
Confirmed that disabling plugin Advanced Gutenberg allowed me to show the "change block type or style" drop down and the blocks in the Add Block panel. (There's no big + button at the bottom of the form, but the small black + icons between blocks work.)
![image](https://user-images.githubusercontent.com/15878723/98042683-f9c9ae00-1df1-11eb-829d-b54451cee649.png)

**Comment by cristianraiber** [comment]
This has been fixed.
