### ISSUE TITLE
Add Math Captcha

### ISSUE THREAD

**Issue by dumketo** [WPChill/gutenberg-forms#178]
Hello bro, 
Can you please math captcha on form... Or tell me how will I use math captcha on this form?? 

Please give me a proper solution I need this badly.

**Comment by munirkamal** [comment]
@dumketo 

This is not something on our priority list todo, right now. There is already reCaptcha, Akismet integration to fight spam.

That said, I have labeled this as a feature request and will consider it if more users request this feature. :) 

Cheers
