### ISSUE TITLE
Suggested edits to the WordPress page

### ISSUE THREAD

**Issue by JoeMurray** [WPChill/gutenberg-forms#183]
Here are some suggested edits to your page on WordPress.com https://docs.google.com/document/d/1f2vPifqIuY5ph-jnAXJnGqoq_IGjqoLETBZiSajv3BI/edit?usp=sharing

CiviCRM is an open source CRM for non-profits that has over 11,000 installations and integrates with WordPress, Drupal, and Joomla. We have a current integration with Caldera Forms and are considering supporting the integration of another. We like the idea of one in Gutenberg. Your development seems to have slowed down unfortunately. How is your adoption rate of 900 trending?

**Comment by JoeMurray** [comment]
See PR at https://github.com/gutenberghub/gutenberg-forms/pull/185

**Comment by cristianraiber** [comment]
Implemented.
