### ISSUE TITLE
Form Entries Not Saved to database if $send_email = true & array_key_exists('email')

### ISSUE THREAD

**Issue by dashcg** [WPChill/gutenberg-forms#187]
I've been struggling with why entries were not being saved for forms. I searched through the code and I believe the culprit is the if statement on line 472 of triggers/email.php

`
472: if ($send_email === true) { 
...
}
`

It seems that these
`                491: if ($record_entries) {
                    Entries::post($newEntry);
                }   
`
which are nestled in some of the if/else statements, should just be completely moved outside of the main statement

From what I found, if you want to email the output _and_ save a form, you cannot add an address in the TO field of the "Email Notification" setting of the parent Gutenberg Form block.

I don't often post on here so I may not be following standards on how to mention bugs or changes.

**Comment by ilangleben19** [comment]
Hi! Just submitted a pull request (#199) which will solve this issue.

It would be great if this could be accepted ASAP - I haven't been able to update the plugin for fear of losing Plugin Editor changes.

**Comment by cristianraiber** [comment]
As of version 2.2.7 this has been fixed.
