### ISSUE TITLE
Recaptcha javascript always added to website

### ISSUE THREAD

**Issue by NicoHood** [WPChill/gutenberg-forms#200]
On my website I can see in the google page speed insights, that a recaptcha javascript is occupying a lot of the load time, even when no form is used at all. I am wondering why this happens. It is only a problem when this plugin is set to active!

Edit: I am not using any repatcha myself, nor any addon to this plugin!

**Comment by KajKandler** [comment]
https://example.com/wp-content/plugins/forms-gutenberg/assets/scripts/recaptcha-render.js?ver=latest loads 132 K

**Comment by NicoHood** [comment]
Isnt there a way to disable this behavior?
