### ISSUE TITLE
Plugin backend is broken in 5.9

### ISSUE THREAD

**Issue by ilangleben19** [WPChill/gutenberg-forms#206]
Plugin backend (in administration area) breaks with WP 5.9. Frontend and email triggers seem to work, but backend shows nothing upon clicking Gutenberg Forms. Dev tools shows an obfuscated React error. Reverting to 5.8.3 resolves completely.

**Comment by andyluak** [comment]
Tomorrow I will issue a fix. Thank you for reporting it.
