### ISSUE TITLE
make it translatable

### ISSUE THREAD

**Issue by ZafarKamal123** [WPChill/gutenberg-forms#63]
We need to be able to translate strings, which are hard-coded now.
Either in .pot files, or https://translate.wordpress.org/

**Comment by simonhammes** [comment]
I would do this by generating .pot (and .json for the Gutenberg .js files!) files with WP-CLI
I can start a pull request

**Comment by ZafarKamal123** [comment]
Sounds Great @simonhammes 👍

**Comment by simonhammes** [comment]
Well .. after doing some research the translate.wordpress.org way sounds better

https://github.com/WordPress/gutenberg/blob/31513b69330f3589db5cf3a3ce3d641331f4e3ad/docs/designers-developers/developers/internationalization.md

We need to decide on a language domain ('cwp-gutenberg-forms'?), make the wp_set_script_translations() call in the init.php file. Then WordPress should automatically pull in (our not yet existing) translation files from translate.wordpress.org (identified by the language domain)

**Comment by ZafarKamal123** [comment]
This feature is under progress.
